package com.vasmarfas.card.tools.developer

data class MimeType(val type: String, val extensions: List<String>, val description: String) {
    val category: String get() = type.substringBefore('/')
}

object MimeTypes {
    private fun m(type: String, extensions: String, description: String) = MimeType(type, extensions.split(' '), description)

    val all: List<MimeType> = listOf(
        m("text/plain", "txt log conf ini", "Plain text"),
        m("text/html", "html htm", "HTML document"),
        m("text/css", "css", "Cascading style sheet"),
        m("text/javascript", "js mjs", "JavaScript"),
        m("text/csv", "csv", "Comma-separated values"),
        m("text/tab-separated-values", "tsv", "Tab-separated values"),
        m("text/markdown", "md markdown", "Markdown"),
        m("text/calendar", "ics ical", "iCalendar"),
        m("text/vcard", "vcf", "vCard contact"),
        m("text/vtt", "vtt", "WebVTT subtitles"),
        m("text/x-python", "py", "Python source"),
        m("text/x-java-source", "java", "Java source"),
        m("text/x-kotlin", "kt kts", "Kotlin source"),
        m("text/x-c", "c h", "C source"),
        m("text/x-c++", "cpp cc hpp", "C++ source"),
        m("text/x-go", "go", "Go source"),
        m("text/x-rust", "rs", "Rust source"),
        m("text/x-ruby", "rb", "Ruby source"),
        m("text/x-sh", "sh bash", "Shell script"),
        m("text/event-stream", "", "Server-sent events"),
        m("application/json", "json map", "JSON"),
        m("application/ld+json", "jsonld", "JSON-LD"),
        m("application/x-ndjson", "ndjson jsonl", "Newline-delimited JSON"),
        m("application/xml", "xml xsd", "XML"),
        m("application/xhtml+xml", "xhtml", "XHTML"),
        m("application/atom+xml", "atom", "Atom feed"),
        m("application/rss+xml", "rss", "RSS feed"),
        m("application/xslt+xml", "xslt xsl", "XSLT stylesheet"),
        m("application/yaml", "yaml yml", "YAML"),
        m("application/toml", "toml", "TOML"),
        m("application/sql", "sql", "SQL script"),
        m("application/graphql", "graphql gql", "GraphQL"),
        m("application/x-www-form-urlencoded", "", "HTML form body"),
        m("multipart/form-data", "", "Multipart form body (file uploads)"),
        m("application/octet-stream", "bin dat", "Arbitrary binary data"),
        m("application/pdf", "pdf", "PDF document"),
        m("application/rtf", "rtf", "Rich Text Format"),
        m("application/msword", "doc dot", "Microsoft Word 97-2003"),
        m("application/vnd.openxmlformats-officedocument.wordprocessingml.document", "docx", "Microsoft Word"),
        m("application/vnd.ms-excel", "xls", "Microsoft Excel 97-2003"),
        m("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx", "Microsoft Excel"),
        m("application/vnd.ms-powerpoint", "ppt", "Microsoft PowerPoint 97-2003"),
        m("application/vnd.openxmlformats-officedocument.presentationml.presentation", "pptx", "Microsoft PowerPoint"),
        m("application/vnd.visio", "vsd", "Microsoft Visio"),
        m("application/x-msaccess", "mdb accdb", "Microsoft Access"),
        m("application/vnd.oasis.opendocument.text", "odt", "OpenDocument text"),
        m("application/vnd.oasis.opendocument.spreadsheet", "ods", "OpenDocument spreadsheet"),
        m("application/vnd.oasis.opendocument.presentation", "odp", "OpenDocument presentation"),
        m("application/vnd.apple.pages", "pages", "Apple Pages"),
        m("application/vnd.apple.numbers", "numbers", "Apple Numbers"),
        m("application/vnd.apple.keynote", "key", "Apple Keynote"),
        m("application/epub+zip", "epub", "EPUB e-book"),
        m("application/x-mobipocket-ebook", "mobi prc", "Mobipocket e-book"),
        m("application/vnd.amazon.ebook", "azw azw3", "Kindle e-book"),
        m("image/vnd.djvu", "djvu djv", "DjVu document"),
        m("application/vnd.ms-xpsdocument", "xps", "XPS document"),
        m("application/postscript", "ps eps ai", "PostScript / Illustrator"),
        m("image/png", "png", "PNG image"),
        m("image/apng", "apng", "Animated PNG"),
        m("image/jpeg", "jpg jpeg jpe", "JPEG image"),
        m("image/gif", "gif", "GIF image"),
        m("image/webp", "webp", "WebP image"),
        m("image/avif", "avif", "AVIF image"),
        m("image/jxl", "jxl", "JPEG XL image"),
        m("image/svg+xml", "svg svgz", "SVG vector image"),
        m("image/bmp", "bmp", "Bitmap image"),
        m("image/tiff", "tif tiff", "TIFF image"),
        m("image/heic", "heic", "HEIC image (Apple)"),
        m("image/heif", "heif", "HEIF image"),
        m("image/vnd.microsoft.icon", "ico", "Windows icon"),
        m("image/vnd.adobe.photoshop", "psd", "Photoshop document"),
        m("image/x-xcf", "xcf", "GIMP image"),
        m("image/vnd.dwg", "dwg", "AutoCAD drawing"),
        m("image/vnd.dxf", "dxf", "AutoCAD DXF"),
        m("audio/mpeg", "mp3", "MP3 audio"),
        m("audio/wav", "wav", "WAV audio"),
        m("audio/ogg", "ogg oga", "Ogg Vorbis audio"),
        m("audio/opus", "opus", "Opus audio"),
        m("audio/flac", "flac", "FLAC audio"),
        m("audio/aac", "aac", "AAC audio"),
        m("audio/mp4", "m4a", "MPEG-4 audio"),
        m("audio/webm", "weba", "WebM audio"),
        m("audio/midi", "mid midi", "MIDI"),
        m("audio/aiff", "aif aiff", "AIFF audio"),
        m("audio/amr", "amr", "AMR speech audio"),
        m("audio/x-ms-wma", "wma", "Windows Media Audio"),
        m("audio/x-mpegurl", "m3u", "M3U playlist"),
        m("video/mp4", "mp4 m4v", "MPEG-4 video"),
        m("video/webm", "webm", "WebM video"),
        m("video/x-matroska", "mkv", "Matroska video"),
        m("video/quicktime", "mov qt", "QuickTime video"),
        m("video/x-msvideo", "avi", "AVI video"),
        m("video/mpeg", "mpeg mpg", "MPEG video"),
        m("video/ogg", "ogv", "Ogg video"),
        m("video/3gpp", "3gp", "3GPP mobile video"),
        m("video/mp2t", "ts", "MPEG transport stream"),
        m("video/x-flv", "flv", "Flash video"),
        m("video/x-ms-wmv", "wmv", "Windows Media Video"),
        m("application/vnd.apple.mpegurl", "m3u8", "HLS playlist"),
        m("application/dash+xml", "mpd", "MPEG-DASH manifest"),
        m("application/x-subrip", "srt", "SubRip subtitles"),
        m("application/ttml+xml", "ttml", "TTML subtitles"),
        m("font/woff", "woff", "WOFF font"),
        m("font/woff2", "woff2", "WOFF2 font"),
        m("font/ttf", "ttf", "TrueType font"),
        m("font/otf", "otf", "OpenType font"),
        m("application/vnd.ms-fontobject", "eot", "Embedded OpenType font"),
        m("application/zip", "zip", "ZIP archive"),
        m("application/gzip", "gz tgz", "Gzip archive"),
        m("application/x-tar", "tar", "Tar archive"),
        m("application/x-7z-compressed", "7z", "7-Zip archive"),
        m("application/vnd.rar", "rar", "RAR archive"),
        m("application/x-bzip2", "bz2", "Bzip2 archive"),
        m("application/x-xz", "xz", "XZ archive"),
        m("application/zstd", "zst", "Zstandard archive"),
        m("application/java-archive", "jar", "Java archive"),
        m("application/vnd.android.package-archive", "apk", "Android package"),
        m("application/x-apple-diskimage", "dmg", "macOS disk image"),
        m("application/x-iso9660-image", "iso", "ISO disk image"),
        m("application/vnd.debian.binary-package", "deb", "Debian package"),
        m("application/x-rpm", "rpm", "RPM package"),
        m("application/x-msi", "msi", "Windows installer"),
        m("application/vnd.microsoft.portable-executable", "exe dll", "Windows executable"),
        m("application/x-chrome-extension", "crx", "Chrome extension"),
        m("application/x-xpinstall", "xpi", "Firefox extension"),
        m("application/wasm", "wasm", "WebAssembly module"),
        m("application/manifest+json", "webmanifest", "Web app manifest"),
        m("application/x-shockwave-flash", "swf", "Flash movie"),
        m("application/x-httpd-php", "php", "PHP script"),
        m("application/x-bittorrent", "torrent", "BitTorrent metainfo"),
        m("application/pkix-cert", "cer crt der", "X.509 certificate"),
        m("application/x-pem-file", "pem", "PEM-encoded certificate or key"),
        m("application/x-pkcs12", "p12 pfx", "PKCS#12 keystore"),
        m("application/pgp-encrypted", "pgp gpg", "PGP encrypted data"),
        m("application/pgp-signature", "asc sig", "PGP signature"),
        m("application/gpx+xml", "gpx", "GPS exchange format"),
        m("application/vnd.google-earth.kml+xml", "kml", "Google Earth KML"),
        m("application/vnd.google-earth.kmz", "kmz", "Google Earth KMZ"),
        m("application/geo+json", "geojson", "GeoJSON"),
        m("model/stl", "stl", "STL 3D model"),
        m("model/obj", "obj", "Wavefront OBJ 3D model"),
        m("model/gltf+json", "gltf", "glTF 3D model"),
        m("model/gltf-binary", "glb", "glTF binary 3D model"),
        m("model/3mf", "3mf", "3D Manufacturing Format"),
        m("model/step", "step stp", "STEP CAD model"),
        m("model/vnd.usdz+zip", "usdz", "Universal Scene Description"),
        m("application/vnd.sqlite3", "sqlite db sqlite3", "SQLite database"),
        m("application/vnd.apache.parquet", "parquet", "Apache Parquet"),
        m("application/vnd.comicbook+zip", "cbz", "Comic book archive (ZIP)"),
        m("application/vnd.comicbook-rar", "cbr", "Comic book archive (RAR)"),
        m("message/rfc822", "eml mht", "Email message"),
        m("application/x-abiword", "abw", "AbiWord document"),
        m("application/vnd.wordperfect", "wpd", "WordPerfect document"),
    )

    fun search(query: String): List<MimeType> {
        val q = query.trim().lowercase().removePrefix(".").removePrefix("*.")
        if (q.isEmpty()) return all
        val byExtension = all.filter { t -> t.extensions.any { it == q } }
        if (byExtension.isNotEmpty()) return byExtension
        return all.filter { t ->
            t.type.contains(q) || t.description.lowercase().contains(q) || t.extensions.any { it.startsWith(q) }
        }
    }
}
