package com.vasmarfas.card.tools.network

data class PortEntry(val port: Int, val protocol: String, val service: String, val description: String)

object WellKnownPorts {
    val all: List<PortEntry> = listOf(
        PortEntry(20, "TCP", "FTP data", "File Transfer Protocol, data channel"),
        PortEntry(21, "TCP", "FTP", "File Transfer Protocol, control"),
        PortEntry(22, "TCP", "SSH", "Secure Shell, SFTP, SCP"),
        PortEntry(23, "TCP", "Telnet", "Unencrypted remote terminal"),
        PortEntry(25, "TCP", "SMTP", "Mail transfer between servers"),
        PortEntry(53, "TCP/UDP", "DNS", "Domain Name System"),
        PortEntry(67, "UDP", "DHCP server", "Dynamic host configuration"),
        PortEntry(68, "UDP", "DHCP client", "Dynamic host configuration"),
        PortEntry(69, "UDP", "TFTP", "Trivial FTP, firmware and PXE"),
        PortEntry(80, "TCP", "HTTP", "Web, unencrypted"),
        PortEntry(88, "TCP/UDP", "Kerberos", "Authentication"),
        PortEntry(110, "TCP", "POP3", "Mail retrieval"),
        PortEntry(111, "TCP/UDP", "rpcbind", "ONC RPC portmapper, NFS"),
        PortEntry(119, "TCP", "NNTP", "Usenet news"),
        PortEntry(123, "UDP", "NTP", "Network Time Protocol"),
        PortEntry(135, "TCP", "MS RPC", "Windows RPC endpoint mapper"),
        PortEntry(137, "UDP", "NetBIOS name", "Windows name service"),
        PortEntry(138, "UDP", "NetBIOS datagram", "Windows browsing"),
        PortEntry(139, "TCP", "NetBIOS session", "SMB over NetBIOS"),
        PortEntry(143, "TCP", "IMAP", "Mail access"),
        PortEntry(161, "UDP", "SNMP", "Monitoring, agents"),
        PortEntry(162, "UDP", "SNMP trap", "Monitoring, notifications"),
        PortEntry(179, "TCP", "BGP", "Border Gateway Protocol"),
        PortEntry(194, "TCP", "IRC", "Internet Relay Chat"),
        PortEntry(389, "TCP/UDP", "LDAP", "Directory access"),
        PortEntry(443, "TCP", "HTTPS", "Web over TLS, HTTP/2, HTTP/3 (UDP)"),
        PortEntry(445, "TCP", "SMB", "Windows file sharing"),
        PortEntry(465, "TCP", "SMTPS", "Mail submission over TLS"),
        PortEntry(500, "UDP", "IKE", "IPsec key exchange"),
        PortEntry(514, "UDP", "Syslog", "Log collection"),
        PortEntry(515, "TCP", "LPD", "Line printer daemon"),
        PortEntry(520, "UDP", "RIP", "Routing Information Protocol"),
        PortEntry(546, "UDP", "DHCPv6 client", "IPv6 host configuration"),
        PortEntry(547, "UDP", "DHCPv6 server", "IPv6 host configuration"),
        PortEntry(548, "TCP", "AFP", "Apple Filing Protocol"),
        PortEntry(554, "TCP/UDP", "RTSP", "Streaming, IP cameras"),
        PortEntry(587, "TCP", "SMTP submission", "Mail submission with STARTTLS"),
        PortEntry(631, "TCP/UDP", "IPP", "Internet Printing Protocol, CUPS"),
        PortEntry(636, "TCP", "LDAPS", "Directory access over TLS"),
        PortEntry(853, "TCP", "DNS over TLS", "Encrypted DNS"),
        PortEntry(873, "TCP", "rsync", "File synchronization"),
        PortEntry(902, "TCP", "VMware", "ESXi remote console"),
        PortEntry(993, "TCP", "IMAPS", "IMAP over TLS"),
        PortEntry(995, "TCP", "POP3S", "POP3 over TLS"),
        PortEntry(1080, "TCP", "SOCKS", "SOCKS proxy"),
        PortEntry(1194, "UDP", "OpenVPN", "VPN"),
        PortEntry(1433, "TCP", "MS SQL", "Microsoft SQL Server"),
        PortEntry(1521, "TCP", "Oracle", "Oracle database listener"),
        PortEntry(1701, "UDP", "L2TP", "VPN tunnelling"),
        PortEntry(1723, "TCP", "PPTP", "Legacy VPN"),
        PortEntry(1812, "UDP", "RADIUS", "Authentication"),
        PortEntry(1813, "UDP", "RADIUS accounting", "Accounting"),
        PortEntry(1883, "TCP", "MQTT", "IoT messaging"),
        PortEntry(1900, "UDP", "SSDP", "UPnP discovery"),
        PortEntry(2049, "TCP/UDP", "NFS", "Network File System"),
        PortEntry(2181, "TCP", "ZooKeeper", "Coordination service"),
        PortEntry(2375, "TCP", "Docker", "Docker daemon, unencrypted"),
        PortEntry(2376, "TCP", "Docker TLS", "Docker daemon over TLS"),
        PortEntry(3000, "TCP", "Dev servers", "Node.js, Grafana, Gitea"),
        PortEntry(3128, "TCP", "Squid", "HTTP proxy"),
        PortEntry(3306, "TCP", "MySQL", "MySQL / MariaDB"),
        PortEntry(3389, "TCP", "RDP", "Remote Desktop"),
        PortEntry(3478, "UDP", "STUN/TURN", "NAT traversal, WebRTC"),
        PortEntry(4443, "TCP", "HTTPS alt", "Alternative HTTPS"),
        PortEntry(4500, "UDP", "IPsec NAT-T", "IPsec through NAT"),
        PortEntry(5000, "TCP", "Dev servers", "Flask, Synology DSM, UPnP"),
        PortEntry(5001, "TCP", "Synology DSM", "DSM over HTTPS, iperf3"),
        PortEntry(5060, "TCP/UDP", "SIP", "VoIP signalling"),
        PortEntry(5061, "TCP", "SIP TLS", "VoIP signalling over TLS"),
        PortEntry(5201, "TCP/UDP", "iperf3", "Bandwidth testing"),
        PortEntry(5222, "TCP", "XMPP", "Jabber client"),
        PortEntry(5353, "UDP", "mDNS", "Multicast DNS, Bonjour"),
        PortEntry(5432, "TCP", "PostgreSQL", "Database"),
        PortEntry(5683, "UDP", "CoAP", "IoT"),
        PortEntry(5900, "TCP", "VNC", "Remote desktop"),
        PortEntry(5938, "TCP", "TeamViewer", "Remote support"),
        PortEntry(6379, "TCP", "Redis", "In-memory store"),
        PortEntry(6443, "TCP", "Kubernetes API", "Cluster API server"),
        PortEntry(6881, "TCP/UDP", "BitTorrent", "Peer traffic"),
        PortEntry(7547, "TCP", "TR-069", "CPE management"),
        PortEntry(8000, "TCP", "HTTP alt", "Development servers"),
        PortEntry(8006, "TCP", "Proxmox VE", "Web interface"),
        PortEntry(8080, "TCP", "HTTP alt", "Proxies, app servers"),
        PortEntry(8083, "TCP", "Vesta / Hestia", "Hosting panels"),
        PortEntry(8088, "TCP", "Asterisk HTTP", "ARI, WebRTC"),
        PortEntry(8123, "TCP", "Home Assistant", "Web interface"),
        PortEntry(8291, "TCP", "Winbox", "MikroTik management"),
        PortEntry(8443, "TCP", "HTTPS alt", "Admin panels"),
        PortEntry(8728, "TCP", "MikroTik API", "RouterOS API"),
        PortEntry(8729, "TCP", "MikroTik API-SSL", "RouterOS API over TLS"),
        PortEntry(8883, "TCP", "MQTT TLS", "IoT messaging over TLS"),
        PortEntry(9000, "TCP", "Portainer / PHP-FPM", "Various"),
        PortEntry(9090, "TCP", "Prometheus / Cockpit", "Monitoring, admin"),
        PortEntry(9091, "TCP", "Transmission", "Torrent client web UI"),
        PortEntry(9100, "TCP", "JetDirect", "Raw printing, node_exporter"),
        PortEntry(9200, "TCP", "Elasticsearch", "Search cluster"),
        PortEntry(9418, "TCP", "Git", "Git protocol"),
        PortEntry(10000, "TCP", "Webmin", "Server admin"),
        PortEntry(10050, "TCP", "Zabbix agent", "Monitoring"),
        PortEntry(10051, "TCP", "Zabbix server", "Monitoring"),
        PortEntry(11211, "TCP", "Memcached", "Cache"),
        PortEntry(25565, "TCP", "Minecraft", "Game server"),
        PortEntry(27017, "TCP", "MongoDB", "Database"),
        PortEntry(32400, "TCP", "Plex", "Media server"),
        PortEntry(51820, "UDP", "WireGuard", "VPN"),
        PortEntry(62078, "TCP", "iOS sync", "Apple device services"),
    )

    val topTcp: List<Int> = listOf(
        21, 22, 23, 25, 53, 80, 81, 88, 110, 111, 135, 139, 143, 161, 389, 443, 445, 465, 515, 548, 554, 587, 631, 636, 873, 902, 993, 995,
        1080, 1433, 1521, 1723, 1883, 2049, 2181, 2375, 3000, 3128, 3306, 3389, 4443, 5000, 5001, 5060, 5201, 5222, 5432, 5900, 6379, 6443,
        8000, 8006, 8008, 8080, 8081, 8083, 8088, 8123, 8291, 8443, 8728, 8729, 8883, 9000, 9090, 9091, 9100, 9200, 10000, 10050, 10051, 11211, 27017, 32400,
    )

    private val byPort: Map<Int, PortEntry> = all.associateBy { it.port }

    fun service(port: Int): String? = byPort[port]?.service

    fun search(query: String): List<PortEntry> {
        val q = query.trim().lowercase()
        if (q.isEmpty()) return all
        return all.filter { it.port.toString().startsWith(q) || it.service.lowercase().contains(q) || it.description.lowercase().contains(q) || it.protocol.lowercase().contains(q) }
    }
}
